name: Generate ClickHouse Blog RSS Feed
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * *"
jobs:
  generate-rss:
    runs-on: ubuntu-latest
    name: Generate RSS
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: Generate RSS
      run: bundle exec clickhouse_blog.rb > clickhouse.xml
    - name: Push to GitHub Pages
      uses: EndBug/add-and-commit@v9
      with:
        add: 'clickhouse.xml'
        new_branch: 'gh-pages'
        push: 'origin gh-pages --force'

